apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline

spec:
  workspaces:
    - name: pipeline-workspace

  params:
    - name: repo-url
    - name: branch
      default: "master"

  tasks:
    - name: clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)

    - name: checkout
      taskRef:
        name: checkout
      params:
        - name: repo-url
          value: "$(params.repo-url)"
        - name: branch
          value: "$(params.branch)"

    - name: lint
      taskRef:
        name: echo
      runAfter:
        - clone
      params:
        - name: message
          value: "Calling Flake8 linter..."

    - name: tests
      taskRef:
        name: echo
      runAfter:
        - lint
      params:
        - name: message
          value: "Running unit tests with PyUnit..."

    - name: build
      taskRef:
        name: echo
      runAfter:
        - tests
      params:
        - name: message
          value: "Building image for $(params.repo-url) ..."

    - name: deploy
      taskRef:
        name: echo
      runAfter:
        - build
      params:
        - name: message
          value: "Deploying $(params.branch) branch of $(params.repo-url) ..."
